name: License Check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Install license-checker
      run: npm install -g license-checker
    - name: Check licenses
      run: license-checker --json --out licenses.json
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: licenses
        path: licenses.json
