name: sbom generation 
on: 
    push: 
        branches: 
        - master 
    pull_request: 

jobs: 
    build: 
        name: SBOM-Generation 
        runs-on: ubuntu-latest 
        steps: 
            #Checkout the product source code
            - name: Checkout code 
              uses: actions/checkout@v3
      
            #Install npm package
            - name: Install npm
              run: npm install
              
            #Install Pyton version 3.x
            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.x
            
            #Install Pip
            - name: Install PIP
              run: pip install requests

            #Generate BOM.XML and output to a file
            - name: Generate SBOM
              uses: CycloneDX/gh-node-module-generatebom@v1              
              with: 
                output: sbom.xml
     
            #Upload SBOM to Dependency-Track
            - name: Upload SBOM to Dependency-Track
              uses: DependencyTrack/gh-upload-sbom@v1.0.0
              with:
                serverhostname: 'dependency.oopsie.wtf' #${{ secrets.DEPENDENCY_TRACK_HOSTNAME }}
                port: '443' #${{ secrets.DEPENDENCY_TRACK_PORT }}
                apikey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
                projectname: ${{ steps.repo.outputs.name }}
                autocreate: true
                bomfilename: 'sbom.xml'
