name: sbom generation 
on: 
    push: 
        branches: 
        - master 
    pull_request: 

jobs: 
    build: 
        name: SBOM-Generation 
        runs-on: ubuntu-latest 
        steps: 
            - name: Checkout code 
              uses: actions/checkout@v2
              
            - name: Install dependencies
              run: npm install
              
            - name: Install Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.x

            - name: Install Dependencies
              run: pip install requests

            - name: Generate SBOM
              uses: CycloneDX/gh-node-module-generatebom@v1              
              with: 
                output: './test.app.bom.xml'
                
            - name: Upload SBOM artifact
              uses: actions/upload-artifact@v2
              with:
                name: sbom
                path: bom.xml

            - name: Get Repository Name
              id: repo
              run: echo "::set-output name=name::$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)"

            - name: Get Latest Project Version
              id: latest_version
              run: |
                response=$(curl -H "X-Api-Key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}" https://dependency.oopsie.wtf/api/v1/project/${{ steps.repo.outputs.name }}/versions?limit=1)
                if [ "$(echo $response | jq '.count')" -eq 0 ]; then
                    echo "::set-output name=version::1.0.0"
                else
                    latest=$(echo $response | jq '.versions[0].version' | tr -d '"')
                    version=$(python -c "import semver; print(semver.bump_patch('$latest'))")
                    echo "::set-output name=version::$version"
                fi

            - name: Upload SBOM to Dependency-Track
              #uses: dependabot/dependabot-core/dependency-track-upload-sbom@v0.1.0
              uses: DependencyTrack/gh-upload-sbom@v1.0.0
              with:
                server: https://dependency.oopsie.wtf/
                api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
                file: sbom.xml
                project_name: ${{ steps.repo.outputs.name }}
                project_version: ${{ steps.latest_version.outputs.version }}
