name: sbom generation 
on: 
    push: 
        branches: 
        - master 
    pull_request: 

jobs: 
    build: 
        name: SBOM-Generation 
        runs-on: ubuntu-20.04 
        steps: 
            - name: Checkout code 
              uses: actions/checkout@v3 
            - name: Install dependencies
              run: npm install
            - name: Generate SBOM
              uses: CycloneDX/cyclonedx-github-action@v2.2              
              with: 
                include_dev_dependencies: true
                output_type: 'all'
                output_file_name: 'sbom.xml'
            - name: Upload SBOM artifact
              uses: actions/upload-artifact@v2
              with:
                name: sbom
                path: sbom.xml
